### ISSUE TITLE
performance degradation / add alerts to know when to restart in prometheus

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrytv-player#6]
Debug, understand and fix the performance degradation of the player if left running for a certain amount of time

**Comment by andybeletsky** [comment]
I would actually suggest looking at replacing our LFU cache lib with a simpler mechanism or perhaps implementing #7 in addition to it to avoid this performance degradation completely.

**Comment by andybeletsky** [comment]
I believe this is no longer an issue.
